package io.github.zzz8688.diagagent.agent.runtime;

public enum StopReason {
    NONE,
    EVIDENCE_SUFFICIENT,
    FINAL_ANSWER_RETURNED,
    INSUFFICIENT_EVIDENCE,
    MAX_TURNS_REACHED,
    TOKEN_BUDGET_EXHAUSTED,
    USER_CANCELLED,
    APPROVAL_DENIED,
    APPROVAL_TIMEOUT,
    REMOTE_SESSION_TERMINATED,
    ENGINE_ERROR,
    INVALID_MODEL_OUTPUT,
    NO_FURTHER_ACTION
}
